FinalMLP_movielenslatest_x1_001_25b6333c:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_002_72fddffa:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_003_321426fe:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_004_498f3e4f:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_005_c4fb69b1:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_006_d3e7c3b6:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_007_d5f5ef88:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_008_c7c48c68:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.4
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_009_2f3f200b:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_010_76b63456:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_011_937df0b7:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_012_4bd3069e:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.2
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_013_c243c097:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_014_80d6dc94:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: [user_id]
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_015_ad76aa8d:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: [item_id]
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
FinalMLP_movielenslatest_x1_016_4ff27d02:
    batch_size: 4096
    dataset_id: movielenslatest_x1_233328b6
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    feature_specs: null
    fs1_context: []
    fs2_context: []
    fs_hidden_units: [800]
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    mlp1_batch_norm: true
    mlp1_dropout: 0.5
    mlp1_hidden_activations: relu
    mlp1_hidden_units: [400]
    mlp2_batch_norm: true
    mlp2_dropout: 0.3
    mlp2_hidden_activations: relu
    mlp2_hidden_units: [800]
    model: FinalMLP
    model_id: FinalMLP_default
    model_root: ./checkpoints/FinalMLP_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    num_heads: 10
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_fs: true
    verbose: 1
